import type { Metadata } from "next";
import { Inter } from "next/font/google";
import { ToastProvider } from '@/components/ui/toast';
import { Toaster } from "@/components/ui/toaster"
import { useToast } from "@/components/ui/use-toast"
import { ThemeProvider } from "@/components/theme-provider"


import "./globals.css";

const inter = Inter({
  subsets: ["latin"],
  display: 'swap',
  variable: '--font-inter',
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en" suppressHydrationWarning>
      <body>
        {/* <ThemeProvider
          attribute="class"
          defaultTheme="system"
          enableSystem
          disableTransitionOnChange
        > */}
          {children}
          {/* </ThemeProvider> */}
        <Toaster />
        <ToastProvider />
      </body>
    </html>
  )
}

// export function DashboardLayout({
//   children,
// }: {
//   children: React.ReactNode
// }) {
//   return <section>{children}</section>; // Dashboard specific layout
// }

